[package]
name = "${{NAME}}"
version = "0.1.0"
edition = "2021"
rust-version = "1.61"
description = "A Tauri App"
authors = ["${{OWNER}}"]
license = ""
repository = ""
default-run = "${{NAME}}"

[build-dependencies]
mdbook-to-example = "0.1.0"

[dependencies]
