name: Run template

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create from template
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'crate-template'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Run main.py
        run: python main.py $GITHUB_REPOSITORY
      - name: Commit changes
        run: |
          git add .
          git commit -m "Initial commit"
          git push
